name: animoo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.3.0
  dotted_border: ^3.1.0
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/

  fonts:
    - family: Otama
      fonts:
        - asset: assets/fonts/otama/Otama-ep.otf

    - family: OriginalSurfer
      fonts:
        - asset: assets/fonts/original_surfer/OriginalSurfer-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins.regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins.medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins.semibold.ttf
          weight: 600
